server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frame?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  typeAliasesPackage:
  mapperLocations: classpath:mapper/*.xml
